import { ProjectItem, CertificateItem } from './types';

export const PROJECTS: ProjectItem[] = [
  {
    id: 'mirror',
    number: '01',
    type: 'FLAGSHIP CONCEPT',
    title: 'Maison Vineet — AI Smart Mirror',
    description: 'A smart-mirror idea that mixes a camera, face detection and simple colour recommendations. I built the concept to explore how an everyday object could become a more useful, interactive interface.',
    tags: ['AI', 'Computer Vision', 'Smart Mirror', 'UI/UX'],
    diagram: 'CAMERA → ANALYSIS → RECOMMENDATION → DISPLAY',
    chip: 'AI + COMPUTER VISION',
    visualType: 'mirror',
    featured: true,
    lastUpdated: 'Sep 15, 2026',
    stars: 58,
  },
  {
    id: 'robot',
    number: '02',
    type: 'ROBOTICS',
    title: 'Human Following Robot',
    description: 'An Arduino-based prototype that uses distance sensing and motor control to follow a person. It was a hands-on way for me to understand the basic sense → decide → move loop used in mobile robots.',
    tags: ['Arduino UNO', 'Ultrasonic', 'Motors', 'Robotics'],
    diagram: 'SENSOR → DISTANCE → CONTROL → MOTOR',
    chip: 'ARDUINO',
    visualType: 'robot',
    link: 'https://www.tinkercad.com/things/ahfEqrPJ7Vg-the-human-following-robot',
    linkLabel: 'Open Tinkercad',
    lastUpdated: 'Aug 28, 2026',
    stars: 34,
  },
  {
    id: 'energy',
    number: '03',
    type: 'EFFICIENCY',
    title: 'Smart Room Energy System',
    description: 'A small room-automation project that switches lighting based on whether the space is being used. The idea is simple: avoid leaving lights on when nobody is there.',
    tags: ['Arduino', 'Motion sensing', 'Automation', 'Energy'],
    diagram: 'OCCUPANCY → LOGIC → RELAY → LIGHT',
    chip: 'SMART AUTOMATION',
    visualType: 'energy',
    link: 'https://www.tinkercad.com/things/8kvdcDqFfjp-smart-room-energy-saving-',
    linkLabel: 'Open Tinkercad',
    lastUpdated: 'Jul 19, 2026',
    stars: 29,
  },
  {
    id: 'security',
    number: '04',
    type: 'SECURITY',
    title: 'OTP Home Security',
    description: 'An ESP32 home-security prototype built around OTP-based access. I used it to explore how a connected device can add an extra verification step before allowing access.',
    tags: ['ESP32', 'OTP', 'IoT', 'Security'],
    diagram: 'REQUEST → OTP → VERIFY → ACCESS',
    chip: 'ESP32',
    visualType: 'security',
    link: 'https://wokwi.com/projects/456276261250529281',
    linkLabel: 'Open Wokwi',
    lastUpdated: 'Sep 02, 2026',
    stars: 46,
  },
  {
    id: 'homeauto',
    number: '05',
    type: 'HOME AUTOMATION',
    title: 'Home Security Automation System',
    description: 'A Tinkercad simulation for a sensor-based home-security setup. It connects sensor events with automated responses and alerts.',
    tags: ['Tinkercad', 'Sensors', 'Automation'],
    diagram: 'SENSOR → EVENT → CONTROLLER → ALERT',
    chip: 'TINKERCAD',
    visualType: 'homeauto',
    link: 'https://www.tinkercad.com/things/cRm4x1Dreyz-home-security-automation-system',
    linkLabel: 'Open Tinkercad',
    lastUpdated: 'Jun 11, 2026',
    stars: 23,
  },
  {
    id: 'qubit',
    number: '06',
    type: 'EXPERIMENTAL WEB',
    title: 'Qubit Lab',
    description: 'A browser-based playground for exploring qubits and quantum gates without needing a real quantum computer. I focused on making the concepts easier to see and interact with.',
    tags: ['JavaScript', 'Quantum', 'Interactive UI'],
    diagram: 'QUBIT → GATE → CIRCUIT → STATE',
    chip: 'QUANTUM UI',
    visualType: 'qubit',
    link: 'https://qubit-lab-chi.vercel.app/',
    linkLabel: 'Open Live',
    lastUpdated: 'May 22, 2026',
    stars: 41,
  },
  {
    id: 'typetrack',
    number: '07',
    type: 'DESKTOP APP',
    title: 'TypeTrack',
    description: 'A simple typing tracker built with web technologies and Electron. It records speed and accuracy and keeps the interface focused on practice.',
    tags: ['HTML', 'CSS', 'JavaScript', 'Electron'],
    diagram: 'INPUT → WPM → ACCURACY → PROGRESS',
    chip: 'ELECTRON',
    visualType: 'typetrack',
    link: 'https://type-tracker-five.vercel.app/',
    linkLabel: 'Open Live',
    lastUpdated: 'Aug 05, 2026',
    stars: 37,
  },
  {
    id: 'railway',
    number: '08',
    type: 'IOT CONCEPT',
    title: 'Smart Railway Platform Safety',
    description: 'A sensor-based railway-platform safety concept that looks for risky situations and triggers alerts. The project is about getting useful warnings to people quickly.',
    tags: ['Sensors', 'Alerts', 'IoT', 'Safety'],
    diagram: 'SENSORS → EVENT → ALERT → RESPONSE',
    chip: 'SAFETY SYSTEM',
    visualType: 'railway',
    lastUpdated: 'Apr 18, 2026',
    stars: 52,
  },
];

export const CERTIFICATES: CertificateItem[] = [
  {
    id: 'vbyld-2027',
    title: 'Viksit Bharat Young Leaders Dialogue (VBYLD) 2027',
    issuer: 'Ministry of Youth Affairs & Sports · Online Quiz on MYBharat · 9 Sep 2026',
    img: '/assets/certificates/vbyld-2027.jpg',
    category: 'participation',
    badge: 'GOVERNMENT / LEADERSHIP',
  },
  {
    id: 'national-space-day-ai-2026',
    title: 'National Space Day 2026 — AI Workshop',
    issuer: 'Bharat Space Education Research Centre · 23 Aug 2026',
    img: '/assets/certificates/national-space-day-ai-2026.jpg',
    category: 'technical',
    badge: 'SPACE & AI',
  },
  {
    id: 'nasa-arset-remote-sensing-2026',
    title: 'NASA ARSET — Fundamentals of Remote Sensing',
    issuer: 'NASA Applied Remote Sensing Training (ARSET) Program · 29 Aug 2026',
    img: '/assets/certificates/nasa-arset-remote-sensing-2026.jpg',
    category: 'learning',
    badge: 'NASA / REMOTE SENSING',
  },
  {
    id: 'ai-workshop',
    title: 'AI Workshop — Artificial Intelligence Workshop',
    issuer: 'Bharat Space Education Research Centre · 25 Apr 2026',
    img: '/assets/certificates/ai-workshop.png',
    category: 'technical',
    badge: 'AI / WORKSHOP',
  },
  {
    id: 'qualcomm-ai-upskilling',
    title: 'AI Upskilling: Technical Foundation',
    issuer: 'Qualcomm Academy · 10 Jun 2026',
    img: '/assets/certificates/qualcomm-ai-upskilling.png',
    category: 'technical',
    badge: 'AI / UPSKILLING',
  },
  {
    id: 'computer-basic',
    title: 'Computer Basic Certificate',
    issuer: 'Future IT College · Grade A',
    img: '/assets/certificates/computer-basic.jpg',
    category: 'technical',
    badge: 'COMPUTER',
  },
  {
    id: 'tb-mukt-bharat',
    title: 'Quiz on TB Mukt Bharat Abhiyan',
    issuer: 'Ministry of Youth Affairs & Sports · 22 Jul 2026',
    img: '/assets/certificates/tb-mukt-bharat.png',
    category: 'participation',
    badge: 'PARTICIPATION',
  },
  {
    id: 'nasha-mukt-yuva',
    title: 'Nasha Mukt Yuva — Recognition',
    issuer: 'Ministry of Youth Affairs & Sports',
    img: '/assets/certificates/nasha-mukt-yuva.png',
    category: 'participation',
    badge: 'RECOGNITION',
  },
  {
    id: 'har-ghar-tiranga',
    title: 'Har Ghar Tiranga Campaign',
    issuer: 'Ministry of Culture · 2025',
    img: '/assets/certificates/har-ghar-tiranga.png',
    category: 'participation',
    badge: 'CAMPAIGN',
  },
  {
    id: 'freedom-movement',
    title: 'Freedom Movement Certificate',
    issuer: 'Internshala · Commemorative participation',
    img: '/assets/certificates/freedom-movement.png',
    category: 'participation',
    badge: 'PARTICIPATION',
  },
  {
    id: 'eshan-battlefield',
    title: 'Eshan Battlefield Series S02 2025',
    issuer: 'Hellfire Club / Eshan College · BGMI participation',
    img: '/assets/certificates/eshan-battlefield.png',
    category: 'participation',
    badge: 'EVENT',
  },
];

export const TIMELINE_ITEMS = [
  {
    step: '01',
    phase: 'START',
    title: 'Explore electronics',
    description: 'I started with Arduino, sensors and small circuits, learning mostly by building and fixing things myself.',
  },
  {
    step: '02',
    phase: 'BUILD',
    title: 'Connect hardware + software',
    description: 'Then I started connecting the hardware, code and interface into complete IoT and automation projects.',
  },
  {
    step: '03',
    phase: 'EXPAND',
    title: 'Experiment with AI & interfaces',
    description: 'Lately I have been experimenting with computer vision, AI-assisted tools and more interactive web interfaces.',
  },
  {
    step: '04',
    phase: 'NEXT',
    title: 'Build things worth using',
    description: 'The next step is turning more of these experiments into reliable projects that people can actually use.',
  },
];

export const TECH_STACK = [
  'Arduino',
  'ESP32',
  'JavaScript',
  'HTML/CSS',
  'Wokwi',
  'Tinkercad',
  'Electron',
  'GitHub',
  'Vercel',
  'Netlify',
  'Firebase',
  'AI tools',
];
